name: wechat_camera_picker
description: A camera picker which is an extension to wechat_assets_picker, but can be run separately.
version: 2.1.0
homepage: https://github.com/fluttercandies/flutter_wechat_camera_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.8.0
  device_info: ^1.0.0
  path_provider: ^1.6.14
  photo_manager: ^1.0.0
  video_player: ^2.0.0
